Raise required compiler to rust 1.67
Required by recent versions of the cc crate.

    error: package `cc v1.0.106` cannot be built because it requires rustc 1.67 or newer, while the currently active rustc version is 1.63.0